// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjdi_w2bKL0K_v_kNTbw4UYV47WZ0_OBA',
    appId: '1:369975490040:web:9a3a0f142bac029b2d120d',
    messagingSenderId: '369975490040',
    projectId: 'money-minder-3c702',
    authDomain: 'money-minder-3c702.firebaseapp.com',
    storageBucket: 'money-minder-3c702.firebasestorage.app',
    measurementId: 'G-D9WKEQYT1R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnKMuyWA40AgjKy-7GuicoJQg2gcr8W30',
    appId: '1:369975490040:android:a6da399add252dcf2d120d',
    messagingSenderId: '369975490040',
    projectId: 'money-minder-3c702',
    storageBucket: 'money-minder-3c702.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3XwyaNr0dc1k0BrqPjom60sPt3wBlEpc',
    appId: '1:369975490040:ios:b46d32676dbfbafb2d120d',
    messagingSenderId: '369975490040',
    projectId: 'money-minder-3c702',
    storageBucket: 'money-minder-3c702.firebasestorage.app',
    iosBundleId: 'com.example.start1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3XwyaNr0dc1k0BrqPjom60sPt3wBlEpc',
    appId: '1:369975490040:ios:b46d32676dbfbafb2d120d',
    messagingSenderId: '369975490040',
    projectId: 'money-minder-3c702',
    storageBucket: 'money-minder-3c702.firebasestorage.app',
    iosBundleId: 'com.example.start1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjdi_w2bKL0K_v_kNTbw4UYV47WZ0_OBA',
    appId: '1:369975490040:web:1b6b74ef1fd947be2d120d',
    messagingSenderId: '369975490040',
    projectId: 'money-minder-3c702',
    authDomain: 'money-minder-3c702.firebaseapp.com',
    storageBucket: 'money-minder-3c702.firebasestorage.app',
    measurementId: 'G-FNL2HV55D4',
  );

}